apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-agent
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:

    processors:
      batch:

    exporters:
      logging:
      otlp:
        endpoint: "otelcol-gateway-collector-headless.ns-gateway:4317"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [batch]
          exporters: [otlp]
